# Generated by Django 3.2.5 on 2021-08-05 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_author', models.CharField(max_length=20)),
                ('q_title', models.CharField(max_length=200)),
                ('q_content', models.TextField()),
                ('q_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='r_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='r_title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_title', models.CharField(max_length=200)),
                ('a_content', models.TextField()),
                ('a_date', models.DateTimeField(auto_now=True)),
                ('a_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.question')),
            ],
        ),
    ]
