# Generated by Django 3.2.5 on 2021-08-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopbasket',
            name='s_amount',
            field=models.IntegerField(default=1),
        ),
    ]
